name: DigitalOcean Registry Cleaner

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no deletions)'
        required: false
        type: boolean
        default: true
      keep_count:
        description: 'Number of recent tags to keep'
        required: false
        type: number
        default: 1
      min_age_days:
        description: 'Minimum age in days before deletion'
        required: false
        type: number
        default: 7
      repositories:
        description: 'Comma-separated list of repositories to clean (leave empty for all)'
        required: false
        type: string
        default: ''
      run_garbage_collection:
        description: 'Run garbage collection after cleanup to reclaim space'
        required: false
        type: boolean
        default: true

jobs:
  clean-registry:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
    - name: Set parameters
      id: params
      run: |
        # Set parameters from inputs or defaults
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "DRY_RUN=${{ inputs.dry_run }}" >> $GITHUB_OUTPUT
          echo "KEEP_COUNT=${{ inputs.keep_count }}" >> $GITHUB_OUTPUT
          echo "MIN_AGE_DAYS=${{ inputs.min_age_days }}" >> $GITHUB_OUTPUT
          echo "REPOSITORIES=${{ inputs.repositories }}" >> $GITHUB_OUTPUT
          echo "RUN_GARBAGE_COLLECTION=${{ inputs.run_garbage_collection }}" >> $GITHUB_OUTPUT
        else
          # Scheduled run defaults - set dry_run to false for automated runs
          echo "DRY_RUN=false" >> $GITHUB_OUTPUT
          echo "KEEP_COUNT=1" >> $GITHUB_OUTPUT
          echo "MIN_AGE_DAYS=7" >> $GITHUB_OUTPUT
          echo "REPOSITORIES=" >> $GITHUB_OUTPUT
          echo "RUN_GARBAGE_COLLECTION=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Clean Registry
      env:
        DRY_RUN: ${{ steps.params.outputs.DRY_RUN }}
        KEEP_COUNT: ${{ steps.params.outputs.KEEP_COUNT }}
        MIN_AGE_DAYS: ${{ steps.params.outputs.MIN_AGE_DAYS }}
        REPOSITORIES: ${{ steps.params.outputs.REPOSITORIES }}
      run: |
        #!/bin/bash
        set -euo pipefail
        
        # Function to calculate days between dates
        days_since() {
          local timestamp="$1"
          local now=$(date +%s)
          local then=$(date -d "$timestamp" +%s 2>/dev/null || date -jf "%Y-%m-%dT%H:%M:%S" "$timestamp" +%s 2>/dev/null)
          echo $(( (now - then) / 86400 ))
        }
        
        # Function to delete a tag
        delete_tag() {
          local repo="$1"
          local tag="$2"
          
          if [[ "$DRY_RUN" == "true" ]]; then
            echo "    [DRY RUN] Would delete: $tag"
          else
            if doctl registry repository delete-tag "$repo" "$tag" --force; then
              echo "    Deleted: $tag"
              TAGS_DELETED="true"
            else
              echo "    Error deleting $tag"
            fi
          fi
        }
        
        # Print configuration
        echo "Starting DigitalOcean Container Registry cleanup..."
        echo "Mode: $([ "$DRY_RUN" == "true" ] && echo "DRY RUN" || echo "LIVE")"
        echo "Keep last $KEEP_COUNT tag(s)"
        echo "Minimum age: $MIN_AGE_DAYS days"
        echo "--------------------------------------------------"
        
        # Get repositories
        if [[ -z "$REPOSITORIES" ]]; then
          echo "Fetching all repositories..."
          repos=$(doctl registry repository list-v2 --output json | jq -r '.[].name')
          repo_count=$(echo "$repos" | wc -l)
          echo "Found $repo_count repositories"
        else
          repos=$(echo "$REPOSITORIES" | tr ',' '\n' | tr -d ' ')
          echo "Processing specified repositories"
        fi
        
        # Process each repository
        while IFS= read -r repo; do
          [[ -z "$repo" ]] && continue
          
          echo ""
          echo "Processing repository: $repo"
          
          # Get tags for repository
          tags_json=$(doctl registry repository list-tags "$repo" --output json 2>/dev/null || echo "[]")
          
          if [[ "$tags_json" == "[]" ]]; then
            echo "  No tags found"
            continue
          fi
          
          # Count total tags
          tag_count=$(echo "$tags_json" | jq 'length')
          echo "  Found $tag_count tags"
          
          # Sort tags by updated_at (newest first) and process
          echo "$tags_json" | jq -r 'sort_by(.updated_at) | reverse | to_entries | .[] | "\(.key)|\(.value.tag)|\(.value.updated_at)"' | \
          while IFS='|' read -r index tag updated_at; do
            # Calculate age in days
            age_days=$(days_since "$updated_at")
            
            # Determine if we should keep or delete
            if [[ $index -lt $KEEP_COUNT ]]; then
              echo "  KEEP: $tag (position: $((index + 1)), age: $age_days days)"
            elif [[ $age_days -lt $MIN_AGE_DAYS ]]; then
              echo "  KEEP: $tag (too new: $age_days days old)"
            else
              echo "  DELETE: $tag (age: $age_days days)"
              delete_tag "$repo" "$tag"
            fi
          done
          
        done <<< "$repos"
        
        echo ""
        echo "Cleanup complete!"
        
        # Track if any tags were deleted
        if [[ "$DRY_RUN" != "true" ]] && [[ -n "$TAGS_DELETED" ]]; then
          echo "TAGS_WERE_DELETED=true" >> $GITHUB_ENV
        else
          echo "TAGS_WERE_DELETED=false" >> $GITHUB_ENV
        fi
    
    - name: Check for Active Garbage Collection
      if: ${{ steps.params.outputs.RUN_GARBAGE_COLLECTION == 'true' && env.TAGS_WERE_DELETED == 'true' }}
      id: gc_check
      run: |
        echo "Checking for active garbage collection..."
        
        # Get active GC if any
        active_gc=$(doctl registry garbage-collection get-active --format ID 2>/dev/null || echo "")
        
        if [[ -n "$active_gc" ]]; then
          echo "Active garbage collection found: $active_gc"
          echo "ACTIVE_GC_EXISTS=true" >> $GITHUB_OUTPUT
        else
          echo "No active garbage collection found"
          echo "ACTIVE_GC_EXISTS=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Run Garbage Collection
      if: ${{ steps.params.outputs.RUN_GARBAGE_COLLECTION == 'true' && env.TAGS_WERE_DELETED == 'true' && steps.gc_check.outputs.ACTIVE_GC_EXISTS == 'false' }}
      run: |
        echo ""
        echo "Starting garbage collection to reclaim space..."
        echo "Note: Registry will be in read-only mode during this process"
        
        # Start garbage collection
        gc_output=$(doctl registry garbage-collection start --include-untagged-manifests --force)
        echo "$gc_output"
        
        # Extract GC UUID from output
        gc_uuid=$(echo "$gc_output" | grep -oE '[a-f0-9-]{36}' | head -1)
        
        if [[ -n "$gc_uuid" ]]; then
          echo "Garbage collection started with UUID: $gc_uuid"
          echo ""
          echo "Note: Garbage collection runs asynchronously and may take 15+ minutes."
          echo "The registry will be in read-only mode during this time."
          echo "You can check the status with: doctl registry garbage-collection get-active"
        else
          echo "Could not extract garbage collection UUID from output"
        fi
    
    - name: Skip Garbage Collection
      if: ${{ steps.params.outputs.RUN_GARBAGE_COLLECTION == 'true' && env.TAGS_WERE_DELETED == 'true' && steps.gc_check.outputs.ACTIVE_GC_EXISTS == 'true' }}
      run: |
        echo ""
        echo "Skipping garbage collection - another garbage collection is already active"
        echo "Only one garbage collection can run at a time per registry"